#SPDX-License-Identifier: MIT-0
---
# Package installation tasks for install-wordpress role

- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install packages (Debian/Ubuntu)
  apt:
    name: "{{ wordpress_packages_debian }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install packages (RedHat/Rocky)
  yum:
    name: "{{ wordpress_packages_redhat }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Remove default Apache index page
  file:
    path: "{{ wordpress_path }}/index.html"
    state: absent