---
- name: Install required packages on Debian/Ubuntu
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mariadb-server
      - wget
      - unzip
    update_cache: yes
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages on Rocky/RedHat
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb-server
      - wget
      - unzip
    state: present
  when: ansible_facts['os_family'] == "RedHat"